			ORG 00H
START: 	MOV A, #01H
			MOV P1, A
			ACALL DELAY

REPEAT1: 	RL A
				MOV P1,A
				ACALL DELAY
				CJNE A, #80H, REPEAT1

REPEAT2:	RR A
				MOV P1,A
				ACALL DELAY
				CJNE A, #01H, REPEAT2

				SJMP START

DELAY:		MOV R0, #80H
AGAIN:		MOV R1, #00FH
HERE:		DJNZ R1, HERE
				DJNZ R0, AGAIN
				RET

				END